### ISSUE TITLE
hacktober-accepted tag related issue

### ISSUE THREAD

**Issue by shreyavaidya2311** [Ishaan28malik/Hacktoberfest-2020#1112]
My PR got merged yesterday without the hacktoberfest-accepted tag. The status corresponding to my activity is as follows -
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by musavveer** [comment]
Even I faced the same issue.
